# Generated by Django 5.2.3 on 2025-07-01 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(help_text='Enter date in the format YYYY-MM-DD (e.g., 1990-06-30)')),
                ('city', models.CharField(choices=[('KHI', 'Karachi'), ('LHR', 'Lahore'), ('ISB', 'Islamabad'), ('NYC', 'New York City'), ('LON', 'London'), ('DEL', 'Delhi'), ('TKY', 'Tokyo'), ('SYD', 'Sydney')], max_length=50)),
                ('country', models.CharField(choices=[('PK', 'Pakistan'), ('IN', 'India'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('AU', 'Australia')], max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.TextField(default='No address provided')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
