# Generated by Django 6.0.5 on 2026-06-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_tickets_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickets",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
